# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Weka Trace Replay Data Generator.

This module provides a data generator that replays Weka KV-cache-tester traces
(e.g., from Hugging Face semianalysisai/cc-traces-weka-*).

KV-Cache Fidelity & Prompt Reconstruction
-----------------------------------------
Weka traces record conversation sessions as a sequence of block hash IDs (representing fixed-size
token blocks, e.g. 16 tokens/block). They do not store the original raw text prompts or completions.
To evaluate the KV-cache scheduler/performance of a target server under identical hit/miss conditions,
the generator must reconstruct conversation prompt text that tokenizes to the exact sequence of block
hashes recorded in the trace.

1. Turn-by-Turn Reconstructor:
   For every request (turn) in a session, the generator uses a deterministic `HashIdRandomGenerator`
   seeded with a combination of base seed, conversation ID, and block hash ID. It samples words from
   a static, public domain corpus (Shakespeare) to construct the prompt and expected assistant response text.
   This guarantees that if the same block hash ID is visited on different turns or worker processes,
   it always maps to the exact same text tokens, producing identical KV-cache keys on the server.

2. Longest Common Prefix (LCP) and Branching:
   During multi-turn conversations, the user may shift topics or backtrack. The generator compares
   the block hashes of consecutive turns (`longest_common_prefix`).
   - If Turn 1 has hashes [H1, H2, H3] and Turn 2 has [H1, H2, H4], the LCP is 2.
   - The reconstructor uses this LCP to rewind the conversation history back to the end of block 2 (H2),
     evicting the text for block H3, before appending the new prompt block H4.
   - This ensures prompt-cache structural alignment matches the trace exactly.

3. History Substitution Rationale:
   The generator pre-reconstructs assistant response text based on the output token lengths in the trace.
   During live replay, the actual text generated by the server is discarded for the purpose of history building.
   Instead, the pre-reconstructed assistant text is appended to construct subsequent turn prompts.

   - Why? If the live model deviates by even 1 token in output length, it shifts the start index of the next
     user prompt. Because KV-cache blocks are aligned on fixed boundaries, this 1-token shift would cause a
     100% cache miss on all subsequent user prompt blocks.
   - History substitution preserves the exact token offsets and boundaries, guaranteeing 100% KV-cache alignment
     under deterministic (temperature=0) benchmarks. Caveat is that this is not always possible when benchmarking
     different models. But this approach is preserved so we can resemble the KV cache tester approach for this
     replay which is what we are trying to emulate.
"""

from dataclasses import dataclass
from concurrent.futures import FIRST_COMPLETED, ProcessPoolExecutor, wait
import hashlib
import json
import logging
import math
import os
from pathlib import Path
import random
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional, Tuple, Union, Annotated, Set
from multiprocessing.managers import SyncManager

from huggingface_hub import hf_hub_download
from pydantic import BaseModel, Field
from transformers import AutoTokenizer

from inference_perf.config import APIConfig, DataConfig
from inference_perf.datagen.replay_graph_session_datagen import (
    ReplaySession,
    ReplayGraphSessionGeneratorBase,
)
from inference_perf.datagen.otel_trace_to_replay_graph import (
    RawCall,
    build_graph,
)
from inference_perf.datagen.replay_graph_types import ReplayMessage
from inference_perf.datagen.weka_compiled_store import (
    CompileIdentity,
    StoredSession,
    WekaCompiledSessionStore,
    max_dupseed_suffix,
    source_trace_id_from_artifact_id,
)
from inference_perf.utils.custom_tokenizer import CustomTokenizer

logger = logging.getLogger(__name__)
_PROCESS_TOKENIZER_CACHE: Dict[str, Any] = {}


# =============================================================================
# Weka Trace Pydantic Models
# =============================================================================


class WekaNormalRequest(BaseModel):
    t: float
    type: Literal["n"]
    model: str
    input_length: int = Field(alias="in")
    output_length: int = Field(alias="out")
    hash_ids: List[int] = Field(default_factory=list)
    api_time: Optional[float] = None
    think_time: Optional[float] = None


class WekaStreamingRequest(BaseModel):
    t: float
    type: Literal["s"]
    model: str
    input_length: int = Field(alias="in")
    output_length: int = Field(alias="out")
    hash_ids: List[int] = Field(default_factory=list)
    api_time: Optional[float] = None
    think_time: Optional[float] = None
    ttft: Optional[float] = None


class WekaSubagentEntry(BaseModel):
    t: float
    type: Literal["subagent"]
    agent_id: str
    subagent_type: str
    duration_ms: Optional[int] = None
    requests: List[WekaNormalRequest] = Field(default_factory=list)
    tool_tokens: int = 0
    system_tokens: int = 0


WekaRequest = Annotated[Union[WekaNormalRequest, WekaStreamingRequest, WekaSubagentEntry], Field(discriminator="type")]


class WekaTrace(BaseModel):
    id: str
    models: List[str]
    block_size: int
    tool_tokens: int = 0
    system_tokens: int = 0
    session_headers: Optional[Dict[str, str]] = None
    requests: List[WekaRequest]


# =============================================================================
# Timeline Timing & Warping
# =============================================================================


@dataclass(frozen=True)
class _RequestTiming:
    timestamp_seconds: float
    delay_ms: Optional[float]


@dataclass(frozen=True)
class _IdleGap:
    raw_start: float
    raw_end: float
    shift_before: float
    cap_seconds: float
    excess_seconds: float


class _IdleGapTimeWarp:
    """Compresses request-start gaps in a trace and maps raw seconds to adjusted seconds."""

    def __init__(self, request_starts: List[float], cap_seconds: float):
        self._gaps: List[_IdleGap] = []
        sorted_starts = sorted(request_starts)
        if not sorted_starts:
            return

        prev_start = sorted_starts[0]
        cumulative_shift = 0.0
        for start in sorted_starts[1:]:
            gap_seconds = start - prev_start
            if gap_seconds > cap_seconds:
                excess = gap_seconds - cap_seconds
                self._gaps.append(
                    _IdleGap(
                        raw_start=prev_start,
                        raw_end=start,
                        shift_before=cumulative_shift,
                        cap_seconds=cap_seconds,
                        excess_seconds=excess,
                    )
                )
                cumulative_shift += excess
            prev_start = start

    def map(self, t_seconds: float) -> float:
        shift = 0.0
        for gap in self._gaps:
            if t_seconds < gap.raw_start:
                return t_seconds - gap.shift_before
            if t_seconds < gap.raw_end:
                local = t_seconds - gap.raw_start
                if local <= gap.cap_seconds:
                    return t_seconds - gap.shift_before
                return gap.raw_start - gap.shift_before + gap.cap_seconds
            shift = gap.shift_before + gap.excess_seconds
        return t_seconds - shift


# =============================================================================
# Hash-ID Based Prompt Synthesis
# =============================================================================


class HashIdRandomGenerator:
    """Deterministic random generator scoped per (trace_id, hash_id)."""

    def __init__(self, base_seed: int):
        self.base_seed = base_seed
        self._trace_id: str = ""
        self._rng = random.Random()

    def set_trace_id(self, trace_id: str) -> None:
        self._trace_id = trace_id

    def reseed_for_hash_id(self, hash_id: int) -> None:
        seed_bytes = hashlib.sha256(f"{self.base_seed}:{self._trace_id}:{hash_id}".encode()).digest()
        self._rng.seed(int.from_bytes(seed_bytes[:8], "big"))

    def randrange(self, stop: int) -> int:
        return self._rng.randrange(stop)

    def choice(self, seq: list[Any]) -> Any:
        return self._rng.choice(seq)


# NOTE: How is this related to decode_token_blocks?
def sample_tokens_from_corpus(
    corpus: List[int],
    num_tokens: int,
    rng_to_use: HashIdRandomGenerator,
    sep_token: Optional[int] = None,
) -> List[int]:
    """Sample tokens from the pre-tokenized corpus using the provided RNG."""
    corpus_len = len(corpus)
    tokens: List[int] = []

    if sep_token is not None:
        tokens.append(sep_token)
        num_tokens -= 1

    start = rng_to_use.randrange(corpus_len)
    end = start + num_tokens

    if end <= corpus_len:
        tokens.extend(corpus[start:end])
    else:
        tokens.extend(corpus[start:])
        tokens.extend(corpus[: end - corpus_len])

    return tokens


# =============================================================================
# Conversation Reconstructor
# =============================================================================


@dataclass
class RoleSegment:
    role: Literal["system", "user", "assistant"]
    block_start: int
    block_count: int
    tokens: List[int]
    content: str


def longest_common_prefix(prev_hash_ids: List[int], curr_hash_ids: List[int]) -> int:
    n = min(len(prev_hash_ids), len(curr_hash_ids))
    for i in range(n):
        if prev_hash_ids[i] != curr_hash_ids[i]:
            return i
    return n


def truncate_synth_buf_at_block(
    segments: List[RoleSegment],
    target_blocks: int,
    block_size: int,
    decode_tokens_to_text: Any,
    prev_partial_tail: int = 0,
) -> Optional[int]:
    if target_blocks <= 0:
        had_segments = len(segments) > 0
        segments.clear()
        return 0 if had_segments else None

    cursor = 0
    for i, seg in enumerate(segments):
        if cursor + seg.block_count < target_blocks:
            cursor += seg.block_count
            continue
        if cursor + seg.block_count == target_blocks:
            disturbed: Optional[int] = None
            if prev_partial_tail > 0 and len(seg.tokens) > 0:
                stripped_n = min(prev_partial_tail, len(seg.tokens))
                seg.tokens = seg.tokens[:-stripped_n]
                seg.content = decode_tokens_to_text(seg.tokens)
                disturbed = i
            deleted_past_boundary = i + 1 < len(segments)
            del segments[i + 1 :]
            if disturbed is None and deleted_past_boundary:
                disturbed = i + 1
            return disturbed
        if cursor == target_blocks:
            del segments[i:]
            return i
        kept_blocks = target_blocks - cursor
        kept_tokens_n = min(len(seg.tokens), kept_blocks * block_size)
        seg.block_count = kept_blocks
        seg.tokens = seg.tokens[:kept_tokens_n]
        seg.content = decode_tokens_to_text(seg.tokens)
        del segments[i + 1 :]
        return i
    return None


class ConversationReconstructor:
    """Reconstructs turn-by-turn prompts and completions deterministically."""

    def __init__(
        self,
        block_size: int,
        decode_block_tokens: Any,
        sample_partial_tail_tokens: Any,
        decode_tokens_to_text: Any,
    ):
        self.block_size = block_size
        self.decode_block_tokens = decode_block_tokens
        self.sample_partial_tail_tokens = sample_partial_tail_tokens
        self.decode_tokens_to_text = decode_tokens_to_text
        self._segments: List[RoleSegment] = []
        self._last_disturbance_at: Optional[int] = None

    def init_turn_0(
        self,
        hash_ids: List[int],
        in_tokens: int,
        tool_tokens: int,
        system_tokens: int,
        seed: str,
    ) -> None:
        bs = self.block_size
        m_full = in_tokens // bs
        partial_tail_tokens_n = in_tokens - m_full * bs
        covered_blocks = min(m_full, len(hash_ids))
        missing_block_tokens = (m_full - covered_blocks) * bs

        cursor = 0
        segs: List[RoleSegment] = []

        if tool_tokens > 0 or system_tokens > 0:
            prefix_tokens = tool_tokens + system_tokens
            prefix_blocks = math.ceil(prefix_tokens / bs)
            if prefix_blocks > 0:
                if prefix_blocks > len(hash_ids):
                    # Fallback or clamp if missing prefix hash blocks
                    prefix_blocks = len(hash_ids)
                if prefix_blocks > 0:
                    seg_tokens = self.decode_block_tokens(hash_ids[cursor : cursor + prefix_blocks])
                    segs.append(
                        RoleSegment(
                            role="system",
                            block_start=cursor,
                            block_count=prefix_blocks,
                            tokens=seg_tokens,
                            content=self.decode_tokens_to_text(seg_tokens),
                        )
                    )
                    cursor += prefix_blocks

        user_blocks = covered_blocks - cursor
        user_tokens = self.decode_block_tokens(hash_ids[cursor : cursor + user_blocks])
        synth_tail_n = missing_block_tokens + partial_tail_tokens_n
        if synth_tail_n > 0:
            user_tokens.extend(self.sample_partial_tail_tokens(synth_tail_n, seed))
        segs.append(
            RoleSegment(
                role="user",
                block_start=cursor,
                block_count=user_blocks,
                tokens=user_tokens,
                content=self.decode_tokens_to_text(user_tokens),
            )
        )

        self._segments = segs
        self._last_disturbance_at = None

    def advance_turn(
        self,
        prev_hash_ids: List[int],
        prev_in_tokens: int,
        prev_out_tokens: int,
        curr_hash_ids: List[int],
        curr_in_tokens: int,
        seed: str,
    ) -> None:
        bs = self.block_size
        m_curr = len(curr_hash_ids)
        m_curr_full = curr_in_tokens // bs
        missing_block_tokens = max(0, (m_curr_full - m_curr) * bs)
        lcp = longest_common_prefix(prev_hash_ids, curr_hash_ids)
        prev_partial_tail = prev_in_tokens % bs

        truncate_disturbance = truncate_synth_buf_at_block(
            self._segments,
            lcp,
            bs,
            decode_tokens_to_text=self.decode_tokens_to_text,
            prev_partial_tail=prev_partial_tail,
        )
        self._last_disturbance_at = truncate_disturbance

        new_blocks = curr_hash_ids[lcp:m_curr]
        new_partial_tail_n = curr_in_tokens % bs
        new_region_tokens = self.decode_block_tokens(new_blocks)
        synth_tail_n = missing_block_tokens + new_partial_tail_n
        if synth_tail_n > 0:
            new_region_tokens.extend(self.sample_partial_tail_tokens(synth_tail_n, seed))
        new_blocks_count = m_curr - lcp

        asst_blocks_target = math.ceil(prev_out_tokens / bs) if prev_out_tokens > 0 else 0
        asst_blocks = min(asst_blocks_target, new_blocks_count)
        asst_emit_size = asst_blocks * bs

        cursor = lcp
        if asst_blocks > 0:
            asst_tokens = new_region_tokens[:asst_emit_size]
            self._segments.append(
                RoleSegment(
                    role="assistant",
                    block_start=cursor,
                    block_count=asst_blocks,
                    tokens=asst_tokens,
                    content=self.decode_tokens_to_text(asst_tokens),
                )
            )
            cursor += asst_blocks

        user_blocks = new_blocks_count - asst_blocks
        user_tokens = new_region_tokens[asst_emit_size:]
        if len(user_tokens) > 0:
            self._segments.append(
                RoleSegment(
                    role="user",
                    block_start=cursor,
                    block_count=user_blocks,
                    tokens=user_tokens,
                    content=self.decode_tokens_to_text(user_tokens),
                )
            )

    def snapshot_messages(self) -> List[Dict[str, str]]:
        return [{"role": s.role, "content": s.content} for s in self._segments]


# =============================================================================
# Intermediate Reconstruction Plan Representations
# =============================================================================


@dataclass
class _ParentPlan:
    trace_id: str
    normals: List[Tuple[int, Union[WekaNormalRequest, WekaStreamingRequest]]]
    subagents: List[Tuple[int, WekaSubagentEntry]]
    block_size: int


@dataclass
class _ChildPlan:
    session_id: str
    parent_trace_id: str
    subagent_index: int
    entry: WekaSubagentEntry
    stream_index: int
    stream_requests: List[WekaNormalRequest]
    block_size: int


@dataclass
class _TraceIdleTiming:
    parent_by_outer_idx: Dict[int, _RequestTiming]
    child_by_session_request: Dict[Tuple[str, int], _RequestTiming]
    subagent_end_by_outer_idx: Dict[int, float]
    subagent_start_by_outer_idx: Dict[int, float]


def _sa_end_seconds(entry: WekaSubagentEntry) -> float:
    duration = entry.duration_ms or 0
    return entry.t + duration / 1000.0


def _subagent_request_absolute_t(entry: WekaSubagentEntry, req: WekaNormalRequest) -> float:
    if req.t + 1e-6 < entry.t:
        return entry.t + req.t
    return req.t


def _pack_into_streams(requests: List[WekaNormalRequest]) -> List[List[WekaNormalRequest]]:
    sorted_reqs = sorted(requests, key=lambda r: r.t)
    streams: List[List[WekaNormalRequest]] = []
    stream_ends: List[float] = []
    for r in sorted_reqs:
        r_end = r.t + (r.api_time or 0.0)
        placed = False
        for i, end in enumerate(stream_ends):
            if end <= r.t:
                streams[i].append(r)
                stream_ends[i] = r_end
                placed = True
                break
        if not placed:
            streams.append([r])
            stream_ends.append(r_end)
    return streams


def _build_trace_idle_timing(
    plan: _ParentPlan,
    child_plans: List[_ChildPlan],
    cap_seconds: float,
) -> _TraceIdleTiming:
    if cap_seconds <= 0:
        parent_by_outer_idx = {}
        prev_t = None
        for outer_idx, req in plan.normals:
            delay_ms: Optional[float] = None if prev_t is None else (req.t - prev_t) * 1000.0
            parent_by_outer_idx[outer_idx] = _RequestTiming(req.t, delay_ms)
            prev_t = req.t

        child_by_session_request = {}
        child_plans_for_trace = [cp for cp in child_plans if cp.parent_trace_id == plan.trace_id]
        for cp in child_plans_for_trace:
            prev_child_t = None
            for k, req in enumerate(cp.stream_requests):
                t = _subagent_request_absolute_t(cp.entry, req)
                delay_ms = None if prev_child_t is None else (t - prev_child_t) * 1000.0
                child_by_session_request[(cp.session_id, k)] = _RequestTiming(t, delay_ms)
                prev_child_t = t

        subagent_end_by_outer_idx = {outer_idx: _sa_end_seconds(entry) for outer_idx, entry in plan.subagents}
        subagent_start_by_outer_idx = {outer_idx: entry.t for outer_idx, entry in plan.subagents}
        return _TraceIdleTiming(
            parent_by_outer_idx=parent_by_outer_idx,
            child_by_session_request=child_by_session_request,
            subagent_end_by_outer_idx=subagent_end_by_outer_idx,
            subagent_start_by_outer_idx=subagent_start_by_outer_idx,
        )

    request_starts: List[float] = [req.t for _, req in plan.normals]

    # Filter child plans for this trace
    child_plans_for_trace = [cp for cp in child_plans if cp.parent_trace_id == plan.trace_id]
    for cp in child_plans_for_trace:
        for req in cp.stream_requests:
            request_starts.append(_subagent_request_absolute_t(cp.entry, req))

    warp = _IdleGapTimeWarp(request_starts, cap_seconds)
    parent_by_outer_idx = {}
    prev_t = None
    for outer_idx, req in plan.normals:
        t = warp.map(req.t)
        delay_ms = None if prev_t is None else (t - prev_t) * 1000.0
        parent_by_outer_idx[outer_idx] = _RequestTiming(t, delay_ms)
        prev_t = t

    child_by_session_request = {}
    for cp in child_plans_for_trace:
        prev_child_t = None
        for k, req in enumerate(cp.stream_requests):
            t = warp.map(_subagent_request_absolute_t(cp.entry, req))
            delay_ms = None if prev_child_t is None else (t - prev_child_t) * 1000.0
            child_by_session_request[(cp.session_id, k)] = _RequestTiming(t, delay_ms)
            prev_child_t = t

    subagent_end_by_outer_idx = {outer_idx: warp.map(_sa_end_seconds(entry)) for outer_idx, entry in plan.subagents}
    subagent_start_by_outer_idx = {outer_idx: warp.map(entry.t) for outer_idx, entry in plan.subagents}
    return _TraceIdleTiming(
        parent_by_outer_idx=parent_by_outer_idx,
        child_by_session_request=child_by_session_request,
        subagent_end_by_outer_idx=subagent_end_by_outer_idx,
        subagent_start_by_outer_idx=subagent_start_by_outer_idx,
    )


def _reconstruct_raw_calls_shared(
    trace: WekaTrace,
    *,
    base_seed: int,
    tokenized_corpus: List[int],
    default_block_size: int,
    trace_idle_gap_cap_seconds: float,
    decode_tokens_to_text: Any,
    use_static_model: bool,
    static_model_name: str,
    model_mapping: Optional[Dict[str, str]],
) -> List[RawCall]:
    cache: Dict[int, List[int]] = {}
    hash_id_rng = HashIdRandomGenerator(base_seed)
    hash_id_rng.set_trace_id(trace.id)
    corpus_size = len(tokenized_corpus)

    configured = model_mapping or {}
    model_map = {m: static_model_name for m in trace.models} if use_static_model else configured

    normals: List[Tuple[int, Union[WekaNormalRequest, WekaStreamingRequest]]] = []
    subagents: List[Tuple[int, WekaSubagentEntry]] = []
    for idx, req in enumerate(trace.requests):
        if isinstance(req, WekaNormalRequest | WekaStreamingRequest):
            normals.append((idx, req))
        elif isinstance(req, WekaSubagentEntry):
            subagents.append((idx, req))

    trace_bs = trace.block_size if hasattr(trace, "block_size") and trace.block_size else default_block_size
    parent_plan = _ParentPlan(trace.id, normals, subagents, block_size=trace_bs)

    child_plans: List[_ChildPlan] = []
    for sa_index, (_, entry) in enumerate(subagents):
        streams = _pack_into_streams(list(entry.requests))
        if not streams:
            streams = [[]]
        multi = len(streams) > 1
        for stream_idx, stream_reqs in enumerate(streams):
            child_sid = f"{trace.id}::sa:{entry.agent_id}"
            if multi:
                child_sid += f":s{stream_idx}"
            child_plans.append(
                _ChildPlan(
                    session_id=child_sid,
                    parent_trace_id=trace.id,
                    subagent_index=sa_index,
                    entry=entry,
                    stream_index=stream_idx,
                    stream_requests=stream_reqs,
                    block_size=trace_bs,
                )
            )

    timing = _build_trace_idle_timing(parent_plan, child_plans, trace_idle_gap_cap_seconds)

    def decode_block_tokens(hash_ids: List[int]) -> List[int]:
        tokens: List[int] = []
        for h in hash_ids:
            cached = cache.get(h)
            if cached is None:
                hash_id_rng.reseed_for_hash_id(h)
                start = hash_id_rng.randrange(corpus_size)
                end = start + trace_bs
                cached = tokenized_corpus[start:end]
                if end > corpus_size:
                    cached = cached + tokenized_corpus[: end - corpus_size]
                cache[h] = cached
            tokens.extend(cached)
        return tokens

    def sample_partial_tail_tokens(n: int, seed: str) -> List[int]:
        if n <= 0:
            return []
        digest = hashlib.sha256(seed.encode()).digest()
        offset = int.from_bytes(digest[:8], "big") % max(corpus_size - n, 1)
        return list(tokenized_corpus[offset : offset + n])

    parent_recon = ConversationReconstructor(
        block_size=trace_bs,
        decode_block_tokens=decode_block_tokens,
        sample_partial_tail_tokens=sample_partial_tail_tokens,
        decode_tokens_to_text=decode_tokens_to_text,
    )
    parent_calls: List[RawCall] = []
    for k, (outer_idx, req) in enumerate(parent_plan.normals):
        seed = f"{trace.id}:turn_{k}:partial_tail"
        if k == 0:
            parent_recon.init_turn_0(
                hash_ids=req.hash_ids,
                in_tokens=req.input_length,
                tool_tokens=trace.tool_tokens,
                system_tokens=trace.system_tokens,
                seed=seed,
            )
        else:
            prev_req = parent_plan.normals[k - 1][1]
            parent_recon.advance_turn(
                prev_hash_ids=prev_req.hash_ids,
                prev_in_tokens=prev_req.input_length,
                prev_out_tokens=prev_req.output_length,
                curr_hash_ids=req.hash_ids,
                curr_in_tokens=req.input_length,
                seed=seed,
            )

        messages_dicts = parent_recon.snapshot_messages()
        messages = [ReplayMessage(role=m["role"], text=m["content"]) for m in messages_dicts]

        t_timing = timing.parent_by_outer_idx[outer_idx]
        t_start_ms = int(t_timing.timestamp_seconds * 1000.0)
        t_end_ms = t_start_ms + int((req.api_time or 0.0) * 1000.0)

        expected_out_text = ""
        if k + 1 < len(parent_plan.normals):
            lookahead = ConversationReconstructor(
                block_size=trace_bs,
                decode_block_tokens=decode_block_tokens,
                sample_partial_tail_tokens=sample_partial_tail_tokens,
                decode_tokens_to_text=decode_tokens_to_text,
            )
            lookahead._segments = [
                RoleSegment(s.role, s.block_start, s.block_count, list(s.tokens), s.content) for s in parent_recon._segments
            ]
            next_req = parent_plan.normals[k + 1][1]
            next_seed = f"{trace.id}:turn_{k + 1}:partial_tail"
            lookahead.advance_turn(
                prev_hash_ids=req.hash_ids,
                prev_in_tokens=req.input_length,
                prev_out_tokens=req.output_length,
                curr_hash_ids=next_req.hash_ids,
                curr_in_tokens=next_req.input_length,
                seed=next_seed,
            )
            for seg in reversed(lookahead._segments):
                if seg.role == "assistant":
                    expected_out_text = seg.content
                    break
        else:
            out_tokens = sample_partial_tail_tokens(req.output_length, f"{trace.id}:final_parent_turn_completion")
            expected_out_text = decode_tokens_to_text(out_tokens)

        parent_calls.append(
            RawCall(
                call_id=f"parent_turn_{k}",
                trace_id=trace.id,
                t_start_ms=t_start_ms,
                t_end_ms=t_end_ms,
                model=model_map.get(req.model, req.model),
                messages=messages,
                out_message=ReplayMessage(role="assistant", text=expected_out_text),
                prompt_tokens=req.input_length,
                completion_tokens=req.output_length,
                temperature=0.0,
                max_tokens_recorded=req.output_length,
            )
        )

    child_calls: List[RawCall] = []
    for cp in child_plans:
        child_recon = ConversationReconstructor(
            block_size=trace_bs,
            decode_block_tokens=decode_block_tokens,
            sample_partial_tail_tokens=sample_partial_tail_tokens,
            decode_tokens_to_text=decode_tokens_to_text,
        )
        for k, creq in enumerate(cp.stream_requests):
            seed = f"{cp.session_id}:turn_{k}:partial_tail"
            if k == 0:
                child_recon.init_turn_0(
                    hash_ids=creq.hash_ids,
                    in_tokens=creq.input_length,
                    tool_tokens=cp.entry.tool_tokens,
                    system_tokens=cp.entry.system_tokens,
                    seed=seed,
                )
            else:
                prev_creq = cp.stream_requests[k - 1]
                child_recon.advance_turn(
                    prev_hash_ids=prev_creq.hash_ids,
                    prev_in_tokens=prev_creq.input_length,
                    prev_out_tokens=prev_creq.output_length,
                    curr_hash_ids=creq.hash_ids,
                    curr_in_tokens=creq.input_length,
                    seed=seed,
                )

            messages_dicts = child_recon.snapshot_messages()
            messages = [ReplayMessage(role=m["role"], text=m["content"]) for m in messages_dicts]

            t_timing = timing.child_by_session_request[(cp.session_id, k)]
            t_start_ms = int(t_timing.timestamp_seconds * 1000.0)
            t_end_ms = t_start_ms + int((creq.api_time or 0.0) * 1000.0)

            expected_out_text = ""
            if k + 1 < len(cp.stream_requests):
                lookahead = ConversationReconstructor(
                    block_size=trace_bs,
                    decode_block_tokens=decode_block_tokens,
                    sample_partial_tail_tokens=sample_partial_tail_tokens,
                    decode_tokens_to_text=decode_tokens_to_text,
                )
                lookahead._segments = [
                    RoleSegment(s.role, s.block_start, s.block_count, list(s.tokens), s.content) for s in child_recon._segments
                ]
                next_creq = cp.stream_requests[k + 1]
                next_seed = f"{cp.session_id}:turn_{k + 1}:partial_tail"
                lookahead.advance_turn(
                    prev_hash_ids=creq.hash_ids,
                    prev_in_tokens=creq.input_length,
                    prev_out_tokens=creq.output_length,
                    curr_hash_ids=next_creq.hash_ids,
                    curr_in_tokens=next_creq.input_length,
                    seed=next_seed,
                )
                for seg in reversed(lookahead._segments):
                    if seg.role == "assistant":
                        expected_out_text = seg.content
                        break
            else:
                out_tokens = sample_partial_tail_tokens(creq.output_length, f"{cp.session_id}:final_turn_completion")
                expected_out_text = decode_tokens_to_text(out_tokens)

            child_calls.append(
                RawCall(
                    call_id=f"sa_{cp.entry.agent_id}_s{cp.stream_index}_turn_{k}",
                    trace_id=trace.id,
                    t_start_ms=t_start_ms,
                    t_end_ms=t_end_ms,
                    model=model_map.get(creq.model, creq.model),
                    messages=messages,
                    out_message=ReplayMessage(role="assistant", text=expected_out_text),
                    prompt_tokens=creq.input_length,
                    completion_tokens=creq.output_length,
                    temperature=0.0,
                    max_tokens_recorded=creq.output_length,
                )
            )

    all_calls = parent_calls + child_calls
    all_calls.sort(key=lambda c: (c.t_start_ms, c.call_id))
    return all_calls


def _build_trace_session_in_process(
    trace_index: int,
    trace: WekaTrace,
    *,
    base_seed: int,
    tokenized_corpus: List[int],
    default_block_size: int,
    trace_idle_gap_cap_seconds: float,
    use_static_model: bool,
    static_model_name: str,
    model_mapping: Optional[Dict[str, str]],
    tokenizer_name_or_path: str,
) -> Tuple[Optional[ReplaySession], Dict[str, Any]]:
    t_total_start = time.perf_counter()
    t_tok_start = time.perf_counter()
    tokenizer = _PROCESS_TOKENIZER_CACHE.get(tokenizer_name_or_path)
    tokenizer_cache_hit = tokenizer is not None
    if tokenizer is None:
        tokenizer = AutoTokenizer.from_pretrained(tokenizer_name_or_path, trust_remote_code=True)
        _PROCESS_TOKENIZER_CACHE[tokenizer_name_or_path] = tokenizer
    tokenizer_load_ms = int((time.perf_counter() - t_tok_start) * 1000)

    def decode_tokens_to_text(tokens: List[int]) -> str:
        decoded = tokenizer.decode(tokens)
        return decoded if isinstance(decoded, str) else " ".join(decoded)

    t_reconstruct_start = time.perf_counter()
    raw_calls = _reconstruct_raw_calls_shared(
        trace,
        base_seed=base_seed,
        tokenized_corpus=tokenized_corpus,
        default_block_size=default_block_size,
        trace_idle_gap_cap_seconds=trace_idle_gap_cap_seconds,
        decode_tokens_to_text=decode_tokens_to_text,
        use_static_model=use_static_model,
        static_model_name=static_model_name,
        model_mapping=model_mapping,
    )
    reconstruct_raw_calls_ms = int((time.perf_counter() - t_reconstruct_start) * 1000)
    if not raw_calls:
        return None, {
            "trace_id": trace.id,
            "trace_index": trace_index,
            "pid": os.getpid(),
            "tokenizer_cache_hit": tokenizer_cache_hit,
            "tokenizer_load_ms": tokenizer_load_ms,
            "reconstruct_raw_calls_ms": reconstruct_raw_calls_ms,
            "build_graph_ms": 0,
            "trace_total_ms": int((time.perf_counter() - t_total_start) * 1000),
            "raw_call_count": 0,
            "event_count": 0,
        }

    t_graph_start = time.perf_counter()
    graph = build_graph(raw_calls, source_file=f"weka_trace_{trace.id}")
    build_graph_ms = int((time.perf_counter() - t_graph_start) * 1000)
    session = ReplaySession(
        session_id=f"wekatrace{trace_index}_{trace.id}",
        source_id=trace.id,
        session_index=trace_index,
        graph=graph,
    )
    return session, {
        "trace_id": trace.id,
        "trace_index": trace_index,
        "pid": os.getpid(),
        "tokenizer_cache_hit": tokenizer_cache_hit,
        "tokenizer_load_ms": tokenizer_load_ms,
        "reconstruct_raw_calls_ms": reconstruct_raw_calls_ms,
        "build_graph_ms": build_graph_ms,
        "trace_total_ms": int((time.perf_counter() - t_total_start) * 1000),
        "raw_call_count": len(raw_calls),
        "event_count": len(graph.events),
    }


# =============================================================================
# WekaTraceReplayDataGenerator Class
# =============================================================================


class WekaTraceReplayDataGenerator(ReplayGraphSessionGeneratorBase):
    """Data generator that replays LLM requests from Weka trace files."""

    def __init__(
        self,
        api_config: APIConfig,
        config: DataConfig,
        tokenizer: Optional[CustomTokenizer],
        mp_manager: Optional[SyncManager] = None,
        base_seed: Optional[int] = None,
        num_workers: int = 1,
        request_timeout: Optional[float] = None,
    ) -> None:
        if not hasattr(config, "weka_trace_replay") or config.weka_trace_replay is None:
            raise ValueError("weka_trace_replay configuration is required for WekaTraceReplayDataGenerator")

        self.weka_config = config.weka_trace_replay

        # Pass the replay config to the parent class
        super().__init__(
            api_config,
            config,
            tokenizer,
            mp_manager=mp_manager,
            base_seed=base_seed,
            num_workers=num_workers,
            replay_config=self.weka_config,
            request_timeout=request_timeout,
        )

        self.mp_manager = mp_manager
        self.num_workers = max(1, num_workers)
        self.base_seed = base_seed if base_seed is not None else 42
        self._trace_headers_by_source_id: Dict[str, Dict[str, str]] = {}
        self._session_headers_by_session_id: Dict[str, Dict[str, str]] = {}
        self._logged_header_sessions: Set[str] = set()
        self._compile_timing_jsonl_path: Optional[Path] = (
            Path(self.weka_config.compile_timing_jsonl_path) if self.weka_config.compile_timing_jsonl_path else None
        )
        if self._compile_timing_jsonl_path is not None:
            self._compile_timing_jsonl_path.parent.mkdir(parents=True, exist_ok=True)
            self._compile_timing_jsonl_path.write_text("", encoding="utf-8")
            self._emit_compile_timing(
                "compile_run_start",
                {
                    "compile_parallelism_mode": self.weka_config.compile_parallelism_mode,
                    "compile_workers_configured": self.weka_config.compile_workers,
                    "compile_chunk_size": self.weka_config.compile_chunk_size,
                    "compile_inflight_limit": self.weka_config.compile_inflight_limit,
                    "num_workers_runtime": self.num_workers,
                },
            )

        # Initialize deterministic prompt corpus
        if self.tokenizer is None:
            raise ValueError("Tokenizer is required for WekaTraceReplayDataGenerator")

        self._tokenized_corpus: List[int] = []
        self._corpus_size = 0
        self._hash_id_rng = HashIdRandomGenerator(self.base_seed)
        self._cache: Dict[int, List[int]] = {}

        store = self._open_compiled_store()
        target = self.weka_config.duplicate_sessions_target
        sessions: Optional[List[ReplaySession]] = None
        store_full_hit = False
        if store is not None and target is not None and store.manifest_path.is_file() and len(store.artifact_ids) >= target:
            store_full_hit = True
            logger.info(
                "Weka compiled store full hit: skipping corpus tokenization and raw trace load; "
                "sampling %d of %d stored session(s) from %s",
                target,
                len(store.artifact_ids),
                store.root,
            )
            t_lookup_start = time.perf_counter()
            sessions, stored_headers = self._load_sampled_sessions_from_store(store, target)
            lookup_ms = int((time.perf_counter() - t_lookup_start) * 1000)
            self._trace_headers_by_source_id.update(stored_headers)
            self._emit_compile_timing(
                "compiled_store_lookup",
                {
                    "stored_count": len(store.artifact_ids),
                    "desired_count": target,
                    "hit_count": target,
                    "miss_count": 0,
                    "full_hit": True,
                    "load_ms": lookup_ms,
                },
            )
            logger.info(
                "Weka compiled store full hit complete: loaded %d session(s) headers=%d load_ms=%d",
                len(sessions),
                len(stored_headers),
                lookup_ms,
            )
            self._emit_compile_timing(
                "session_build_complete",
                {
                    "session_count": len(sessions),
                    "session_build_ms": lookup_ms,
                    "full_hit": True,
                },
            )
        else:
            if store is None:
                logger.info("Weka compiled store: compiled_store_path unset; compiling from raw traces")
            elif target is None:
                logger.info(
                    "Weka compiled store: path=%s stored=%d duplicate_sessions_target unset; "
                    "loading unique traces then lookup/write-through (no skip-raw-load)",
                    store.root,
                    len(store.artifact_ids),
                )
            elif not store.manifest_path.is_file():
                logger.info(
                    "Weka compiled store: empty store at %s; tokenizing corpus and compiling target=%d from raw traces",
                    store.root,
                    target,
                )
            else:
                logger.info(
                    "Weka compiled store partial miss: path=%s stored=%d target=%d filling=%d; "
                    "tokenizing corpus and loading raw traces",
                    store.root,
                    len(store.artifact_ids),
                    target,
                    target - len(store.artifact_ids),
                )
            self._tokenize_prompt_corpus()
            t_trace_load_start = time.perf_counter()
            traces = self._load_weka_traces()
            trace_load_ms = int((time.perf_counter() - t_trace_load_start) * 1000)
            logger.info("Weka raw trace load: %d unique trace(s) in %d ms", len(traces), trace_load_ms)
            self._emit_compile_timing(
                "trace_load",
                {
                    "trace_count": len(traces),
                    "trace_load_ms": trace_load_ms,
                },
            )
            self._trace_headers_by_source_id = {t.id: dict(t.session_headers) for t in traces if t.session_headers}
            t_session_build_start = time.perf_counter()
            sessions = self._build_sessions_from_traces(traces, store=store)
            session_build_ms = int((time.perf_counter() - t_session_build_start) * 1000)
            self._emit_compile_timing(
                "session_build_complete",
                {
                    "session_count": len(sessions),
                    "session_build_ms": session_build_ms,
                },
            )
        t_schedule_start = time.perf_counter()
        assert sessions is not None
        self.initialize_sessions(sessions)
        self._session_headers_by_session_id = {
            session.session_id: dict(self._trace_headers_by_source_id[session.source_id])
            for session in self.sessions
            if session is not None and session.source_id in self._trace_headers_by_source_id
        }
        if self._session_headers_by_session_id:
            logger.info(
                "Weka replay session headers enabled for %d session(s) (store_full_hit=%s)",
                len(self._session_headers_by_session_id),
                store_full_hit,
            )
        schedule_build_ms = int((time.perf_counter() - t_schedule_start) * 1000)
        self._emit_compile_timing(
            "initialize_sessions_complete",
            {
                "schedule_event_count": len(self.all_events),
                "initialize_sessions_ms": schedule_build_ms,
            },
        )
        self._emit_compile_timing("compile_run_end", {})

    def _emit_compile_timing(self, event: str, payload: Dict[str, Any]) -> None:
        if self._compile_timing_jsonl_path is None:
            return

        mode = self.weka_config.compile_parallelism_mode
        record = {
            "ts": datetime.now(timezone.utc).isoformat(),
            "event": event,
            "mode": mode,
            "is_parallel": mode == "process",
            "compile_workers": self.weka_config.compile_workers if mode == "process" else 1,
            "compile_chunk_size": self.weka_config.compile_chunk_size if mode == "process" else 1,
            "compile_inflight_limit": self.weka_config.compile_inflight_limit if mode == "process" else None,
        }
        record.update(payload)
        with self._compile_timing_jsonl_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\n")

    def _prompt_corpus_path(self) -> Path:
        if self.config and self.config.corpus_file_path:
            return Path(self.config.corpus_file_path).expanduser().resolve()
        return (Path(__file__).resolve().parents[1] / "assets" / "shakespeare.txt").resolve()

    def _tokenizer_name_or_path(self) -> str:
        assert self.tokenizer is not None
        tokenizer_instance = self.tokenizer.get_tokenizer()
        name = getattr(tokenizer_instance, "name_or_path", "") or ""
        return name if isinstance(name, str) else ""

    def _build_compile_identity(self) -> CompileIdentity:
        corpus_path = self._prompt_corpus_path()
        if not corpus_path.is_file():
            raise FileNotFoundError(f"Prompt corpus file not found: {corpus_path}")
        return CompileIdentity(
            tokenizer_name_or_path=self._tokenizer_name_or_path(),
            corpus_path=str(corpus_path),
            corpus_byte_size=corpus_path.stat().st_size,
            base_seed=self.base_seed,
            default_block_size=self.weka_config.default_block_size,
            trace_idle_gap_cap_seconds=self.weka_config.trace_idle_gap_cap_seconds,
        )

    def _tokenize_prompt_corpus(self) -> None:
        corpus_path = self._prompt_corpus_path()
        if not corpus_path.is_file():
            raise FileNotFoundError(f"Prompt corpus file not found: {corpus_path}")

        t_corpus_read_start = time.perf_counter()
        corpus_text = corpus_path.read_text(encoding="utf-8")
        corpus_read_ms = int((time.perf_counter() - t_corpus_read_start) * 1000)
        logger.info(f"Loaded prompt corpus from: {corpus_path} ({len(corpus_text)} chars)")

        assert self.tokenizer is not None
        base_prompt = "Pick as many lines as you can from these poem lines:\n"
        t_corpus_tokenize_start = time.perf_counter()
        self._tokenized_corpus = self.tokenizer.get_tokenizer().encode(base_prompt + corpus_text)
        corpus_tokenize_ms = int((time.perf_counter() - t_corpus_tokenize_start) * 1000)
        self._corpus_size = len(self._tokenized_corpus)
        self._emit_compile_timing(
            "corpus_tokenization",
            {
                "corpus_path": str(corpus_path),
                "corpus_char_count": len(corpus_text),
                "tokenized_corpus_size": self._corpus_size,
                "corpus_read_ms": corpus_read_ms,
                "corpus_tokenize_ms": corpus_tokenize_ms,
            },
        )

    def _open_compiled_store(self) -> Optional[WekaCompiledSessionStore]:
        store_path = self.weka_config.compiled_store_path
        if not store_path:
            return None
        logger.info("Weka compiled store: opening %s", store_path)
        store = WekaCompiledSessionStore(Path(store_path), self._build_compile_identity())
        store.load()
        return store

    def _replay_session_from_stored(self, stored: StoredSession, index: int) -> ReplaySession:
        return ReplaySession(
            session_id=f"wekatrace{index}_{stored.artifact_id}",
            source_id=stored.artifact_id,
            session_index=index,
            graph=stored.graph,
        )

    def _headers_from_stored(self, stored: StoredSession) -> Dict[str, Dict[str, str]]:
        if not stored.session_headers:
            return {}
        return {stored.artifact_id: dict(stored.session_headers)}

    def _load_sampled_sessions_from_store(
        self, store: WekaCompiledSessionStore, target: int
    ) -> Tuple[List[ReplaySession], Dict[str, Dict[str, str]]]:
        ids = list(store.artifact_ids)
        random.seed(self.base_seed)
        random.shuffle(ids)
        selected = ids[:target]
        logger.info(
            "Weka compiled store: sampled %d of %d artifact(s) with base_seed=%s",
            len(selected),
            len(store.artifact_ids),
            self.base_seed,
        )
        sessions: List[ReplaySession] = []
        headers: Dict[str, Dict[str, str]] = {}
        for index, stored in enumerate(store.read_sessions(selected)):
            sessions.append(self._replay_session_from_stored(stored, index))
            headers.update(self._headers_from_stored(stored))
        random.seed(self.base_seed)
        random.shuffle(sessions)
        return sessions, headers

    def _load_all_stored_sessions(
        self, store: WekaCompiledSessionStore
    ) -> Tuple[List[ReplaySession], Dict[str, Dict[str, str]]]:
        sessions: List[ReplaySession] = []
        headers: Dict[str, Dict[str, str]] = {}
        for index, stored in enumerate(store.read_sessions(list(store.artifact_ids))):
            sessions.append(self._replay_session_from_stored(stored, index))
            headers.update(self._headers_from_stored(stored))
        return sessions, headers

    @staticmethod
    def _reassign_session_ids(sessions: List[ReplaySession]) -> None:
        for index, session in enumerate(sessions):
            session.session_id = f"wekatrace{index}_{session.source_id}"
            session.session_index = index

    def _write_through_sessions(
        self,
        store: WekaCompiledSessionStore,
        sessions: List[ReplaySession],
        traces: List[WekaTrace],
    ) -> None:
        if not sessions:
            logger.info("Weka compiled store: write-through skipped (no newly compiled sessions) path=%s", store.root)
            return
        traces_by_id = {trace.id: trace for trace in traces}
        t_write_start = time.perf_counter()
        stored_sessions: List[StoredSession] = []
        for session in sessions:
            trace = traces_by_id.get(session.source_id)
            headers: Optional[Dict[str, str]] = None
            if trace is not None and trace.session_headers:
                headers = dict(trace.session_headers)
            elif session.source_id in self._trace_headers_by_source_id:
                headers = dict(self._trace_headers_by_source_id[session.source_id])
            stored_sessions.append(
                StoredSession(
                    artifact_id=session.source_id,
                    source_trace_id=source_trace_id_from_artifact_id(session.source_id),
                    session_headers=headers,
                    graph=session.graph,
                )
            )
        store.write_sessions(stored_sessions)
        store.write_manifest()
        write_ms = int((time.perf_counter() - t_write_start) * 1000)
        written_count = len(stored_sessions)
        self._emit_compile_timing(
            "compiled_store_write",
            {
                "written_count": written_count,
                "write_ms": write_ms,
            },
        )
        logger.info(
            "Weka compiled store write-through: wrote %d session(s) to %s in %d ms", written_count, store.root, write_ms
        )

    def _expand_traces_for_duplication_target(
        self,
        traces: List[WekaTrace],
        stored_artifact_ids: Optional[Set[str]] = None,
        desired_count: Optional[int] = None,
    ) -> List[WekaTrace]:
        """Expand traces to duplicate_sessions_target *before* reconstruction.

        This is Weka-specific: token synthesis is seeded by trace.id. Duplicating
        already-built ReplaySession graphs reuses identical synthesized text. By
        duplicating trace records first and assigning deterministic synthetic IDs,
        each duplicate is reconstructed with a distinct seed scope.

        When ``stored_artifact_ids`` is set, only traces whose ids are not already
        in the store are returned, using today's global ``__dupseed`` counter
        continued from the max suffix already present in the store.
        """
        target = desired_count if desired_count is not None else self.weka_config.duplicate_sessions_target
        if target is None:
            return traces
        if not traces:
            return traces

        if stored_artifact_ids is None:
            if len(traces) >= target:
                return traces

            expanded: List[WekaTrace] = list(traces)
            dup_counter = 0
            src_idx = 0
            while len(expanded) < target:
                src = traces[src_idx % len(traces)]
                src_idx += 1
                dup_counter += 1
                synthetic_trace_id = f"{src.id}__dupseed{dup_counter}"
                expanded.append(src.model_copy(update={"id": synthetic_trace_id}))

            self._emit_compile_timing(
                "trace_duplication_prebuild",
                {
                    "original_trace_count": len(traces),
                    "expanded_trace_count": len(expanded),
                    "duplicate_sessions_target": target,
                },
            )
            logger.info(
                "Weka prebuild duplication expanded traces from %d to %d (target=%d)",
                len(traces),
                len(expanded),
                target,
            )
            return expanded

        need = target - len(stored_artifact_ids)
        if need <= 0:
            return []

        new_traces: List[WekaTrace] = []
        for trace in traces:
            if trace.id not in stored_artifact_ids:
                new_traces.append(trace)
                if len(new_traces) >= need:
                    break

        dup_counter = max_dupseed_suffix(stored_artifact_ids)
        src_idx = 0
        used_ids: Set[str] = set(stored_artifact_ids) | {t.id for t in new_traces}
        while len(new_traces) < need:
            src = traces[src_idx % len(traces)]
            src_idx += 1
            dup_counter += 1
            synthetic_trace_id = f"{src.id}__dupseed{dup_counter}"
            if synthetic_trace_id in used_ids:
                continue
            used_ids.add(synthetic_trace_id)
            new_traces.append(src.model_copy(update={"id": synthetic_trace_id}))

        if any("__dupseed" in trace.id for trace in new_traces):
            self._emit_compile_timing(
                "trace_duplication_prebuild",
                {
                    "original_trace_count": len(traces),
                    "expanded_trace_count": len(stored_artifact_ids) + len(new_traces),
                    "duplicate_sessions_target": target,
                    "stored_artifact_count": len(stored_artifact_ids),
                    "new_compile_count": len(new_traces),
                },
            )
            logger.info(
                "Weka store-aware prebuild duplication: stored=%d new=%d target=%d",
                len(stored_artifact_ids),
                len(new_traces),
                target,
            )
        return new_traces

    def initialize_sessions(self, sessions: List[ReplaySession]) -> None:
        """Initialize sessions without base graph-level duplication.

        Weka duplicates are expanded pre-build in _expand_traces_for_duplication_target.
        Prevent ReplayGraphSessionGeneratorBase.initialize_sessions from duplicating
        identical already-built graphs again.
        """
        replay_cfg = self.replay_config
        if replay_cfg is None or replay_cfg.duplicate_sessions_target is None:
            return super().initialize_sessions(sessions)

        original_target = replay_cfg.duplicate_sessions_target
        replay_cfg.duplicate_sessions_target = None
        try:
            super().initialize_sessions(sessions)
        finally:
            replay_cfg.duplicate_sessions_target = original_target

    def _load_weka_traces(self) -> List[WekaTrace]:
        """Loads traces from local files/dirs or a Hugging Face dataset.

        Local sources support:
        - `.json`: one Weka trace object per file
        - `.jsonl`: one Weka trace object per line
        """
        raw_traces: List[WekaTrace] = []
        max_entries = self.weka_config.num_dataset_entries

        def _append_with_cap(traces_in_file: List[WekaTrace]) -> bool:
            """Append traces up to max_entries; return True when cap reached."""
            remaining = max_entries - len(raw_traces)
            if remaining <= 0:
                return True
            raw_traces.extend(traces_in_file[:remaining])
            return len(raw_traces) >= max_entries

        if self.weka_config.trace_directory:
            trace_dir = Path(self.weka_config.trace_directory)
            if not trace_dir.exists() or not trace_dir.is_dir():
                raise ValueError(f"Trace directory does not exist or is not a directory: {trace_dir}")
            files = sorted(list(trace_dir.glob("*.json")) + list(trace_dir.glob("*.jsonl")))
            if not files:
                raise ValueError(f"No JSON/JSONL files found in {trace_dir}")

            for f in files:
                if len(raw_traces) >= max_entries:
                    break
                try:
                    traces_in_file = self._load_traces_from_local_file(f)
                    if _append_with_cap(traces_in_file):
                        break
                except Exception as e:
                    logger.error(f"Failed to load trace {f.name}: {e}")
                    if not self.weka_config.skip_invalid_files:
                        raise

        elif self.weka_config.trace_files:
            for path in self.weka_config.trace_files:
                if len(raw_traces) >= max_entries:
                    break
                f = Path(path)
                if not f.is_file():
                    raise ValueError(f"Trace file does not exist: {path}")
                if f.suffix.lower() not in {".json", ".jsonl"}:
                    raise ValueError(f"Trace file must be a .json or .jsonl file: {path}")
                try:
                    traces_in_file = self._load_traces_from_local_file(f)
                    if _append_with_cap(traces_in_file):
                        break
                except Exception as e:
                    logger.error(f"Failed to load trace {f.name}: {e}")
                    if not self.weka_config.skip_invalid_files:
                        raise

        elif self.weka_config.hf_dataset_path:
            repo_id = self.weka_config.hf_dataset_path
            if isinstance(repo_id, dict):
                repo_id = repo_id["path"]
            logger.info(f"Downloading Weka traces from Hugging Face dataset: {repo_id}")
            try:
                # Use raw file download to bypass buggy Feature-type validation in datasets
                local_path = hf_hub_download(repo_id=repo_id, filename="traces.jsonl", repo_type="dataset")
                logger.info(f"Trace file downloaded to {local_path}")

                with open(local_path, "r", encoding="utf-8") as file_stream:
                    for line_idx, line in enumerate(file_stream):
                        if line_idx >= self.weka_config.num_dataset_entries:
                            break
                        if line.strip():
                            try:
                                blob = json.loads(line)
                                raw_traces.append(WekaTrace.model_validate(blob))
                            except Exception as e:
                                logger.error(f"Failed to validate row {line_idx}: {e}")
                                if not self.weka_config.skip_invalid_files:
                                    raise
            except Exception as e:
                raise ValueError(f"Failed to load Hugging Face dataset {repo_id}: {e}") from e

        # Ensure unique trace IDs
        unique_traces: Dict[str, WekaTrace] = {}
        for trace in raw_traces:
            if trace.id in unique_traces:
                raise ValueError(f"Duplicate trace ID found: {trace.id}")
            unique_traces[trace.id] = trace

        return list(unique_traces.values())

    def _load_traces_from_local_file(self, file_path: Path) -> List[WekaTrace]:
        """Load Weka traces from one local `.json` or `.jsonl` file."""
        suffix = file_path.suffix.lower()
        if suffix == ".json":
            blob = json.loads(file_path.read_text(encoding="utf-8"))
            return [WekaTrace.model_validate(blob)]
        if suffix == ".jsonl":
            traces: List[WekaTrace] = []
            with file_path.open("r", encoding="utf-8") as file_stream:
                for line_idx, line in enumerate(file_stream, start=1):
                    if not line.strip():
                        continue
                    try:
                        blob = json.loads(line)
                        traces.append(WekaTrace.model_validate(blob))
                    except Exception as e:
                        logger.error(f"Failed to validate row {line_idx} in {file_path.name}: {e}")
                        if not self.weka_config.skip_invalid_files:
                            raise
            return traces
        raise ValueError(f"Unsupported trace file extension for {file_path}; expected .json or .jsonl")

    def _build_sessions_from_traces(
        self,
        traces: List[WekaTrace],
        store: Optional[WekaCompiledSessionStore] = None,
    ) -> List[ReplaySession]:
        if store is None:
            logger.info("Weka session build: store unset; compiling %d loaded unique trace(s)", len(traces))
            traces = self._expand_traces_for_duplication_target(traces)
            sessions = self._compile_trace_list(traces)
            random.seed(self.base_seed)
            random.shuffle(sessions)
            logger.info("Weka session build: compiled %d session(s) without store", len(sessions))
            return sessions

        target = self.weka_config.duplicate_sessions_target
        stored_ids = set(store.artifact_ids)

        if target is None:
            t_lookup_start = time.perf_counter()
            stored_by_id: Dict[str, ReplaySession] = {}
            stored_headers: Dict[str, Dict[str, str]] = {}
            hit_ids = [trace.id for trace in traces if store.contains(trace.id)]
            to_compile = [trace for trace in traces if not store.contains(trace.id)]
            for index, stored in enumerate(store.read_sessions(hit_ids)):
                stored_by_id[stored.artifact_id] = self._replay_session_from_stored(stored, index)
                stored_headers.update(self._headers_from_stored(stored))
            lookup_ms = int((time.perf_counter() - t_lookup_start) * 1000)
            self._trace_headers_by_source_id.update(stored_headers)
            self._emit_compile_timing(
                "compiled_store_lookup",
                {
                    "stored_count": len(stored_ids),
                    "desired_count": len(traces),
                    "hit_count": len(stored_by_id),
                    "miss_count": len(to_compile),
                    "full_hit": False,
                    "load_ms": lookup_ms,
                },
            )
            logger.info(
                "Weka compiled store unique-id lookup: stored=%d unique_traces=%d hits=%d misses=%d load_ms=%d",
                len(stored_ids),
                len(traces),
                len(stored_by_id),
                len(to_compile),
                lookup_ms,
            )
            compiled = self._compile_trace_list(to_compile)
            self._write_through_sessions(store, compiled, to_compile)
            sessions = [stored_by_id[trace.id] for trace in traces if trace.id in stored_by_id]
            sessions.extend(compiled)
            self._reassign_session_ids(sessions)
            random.seed(self.base_seed)
            random.shuffle(sessions)
            logger.info(
                "Weka compiled store unique-id path complete: reused=%d compiled=%d total=%d",
                len(stored_by_id),
                len(compiled),
                len(sessions),
            )
            return sessions

        t_lookup_start = time.perf_counter()
        stored_sessions, stored_headers = self._load_all_stored_sessions(store)
        lookup_ms = int((time.perf_counter() - t_lookup_start) * 1000)
        logger.info(
            "Weka compiled store fill: loaded %d stored session(s) in %d ms",
            len(stored_sessions),
            lookup_ms,
        )
        self._trace_headers_by_source_id.update(stored_headers)
        need = target - len(stored_ids)
        to_compile = self._expand_traces_for_duplication_target(traces, stored_artifact_ids=stored_ids, desired_count=target)
        logger.info(
            "Weka compiled store fill: stored=%d target=%d unique_raw=%d compiling=%d load_ms=%d",
            len(stored_ids),
            target,
            len(traces),
            len(to_compile),
            lookup_ms,
        )
        self._emit_compile_timing(
            "compiled_store_lookup",
            {
                "stored_count": len(stored_ids),
                "desired_count": target,
                "hit_count": len(stored_ids),
                "miss_count": max(0, need),
                "full_hit": False,
                "load_ms": lookup_ms,
            },
        )
        for trace in to_compile:
            if trace.session_headers:
                self._trace_headers_by_source_id[trace.id] = dict(trace.session_headers)
        compiled = self._compile_trace_list(to_compile)
        self._write_through_sessions(store, compiled, to_compile)
        sessions = list(stored_sessions) + compiled
        if len(sessions) < target:
            raise ValueError(
                f"Weka compiled store could not assemble {target} sessions "
                f"(stored={len(stored_sessions)}, newly_compiled={len(compiled)}). "
                "Increase num_dataset_entries, fix invalid traces, or lower duplicate_sessions_target."
            )
        if len(sessions) > target:
            sessions = sessions[:target]
        self._reassign_session_ids(sessions)
        random.seed(self.base_seed)
        random.shuffle(sessions)
        logger.info(
            "Weka compiled store fill complete: stored=%d newly_compiled=%d assembled=%d",
            len(stored_sessions),
            len(compiled),
            len(sessions),
        )
        return sessions

    def _compile_trace_list(self, traces: List[WekaTrace]) -> List[ReplaySession]:
        if not traces:
            logger.info("Weka compile: no traces to reconstruct")
            return []
        mode = self.weka_config.compile_parallelism_mode
        logger.info("Weka compile: reconstructing %d trace(s) mode=%s", len(traces), mode)
        if mode == "process" and len(traces) > 1:
            return self._build_sessions_from_traces_parallel(traces)
        return self._build_sessions_from_traces_sequential(traces)

    def _build_sessions_from_traces_sequential(self, traces: List[WekaTrace]) -> List[ReplaySession]:
        sessions: List[ReplaySession] = []
        self._emit_compile_timing(
            "session_build_mode",
            {
                "effective_mode": "sequential",
                "trace_count": len(traces),
            },
        )

        for trace_index, trace in enumerate(traces):
            try:
                t_trace_start = time.perf_counter()
                t_reconstruct_start = time.perf_counter()
                raw_calls = self._reconstruct_raw_calls(trace)
                reconstruct_raw_calls_ms = int((time.perf_counter() - t_reconstruct_start) * 1000)
                if not raw_calls:
                    self._emit_compile_timing(
                        "trace_compile",
                        {
                            "trace_id": trace.id,
                            "trace_index": trace_index,
                            "execution_mode": "sequential",
                            "reconstruct_raw_calls_ms": reconstruct_raw_calls_ms,
                            "build_graph_ms": 0,
                            "trace_total_ms": int((time.perf_counter() - t_trace_start) * 1000),
                            "raw_call_count": 0,
                            "event_count": 0,
                        },
                    )
                    continue

                t_graph_start = time.perf_counter()
                graph = build_graph(raw_calls, source_file=f"weka_trace_{trace.id}")
                build_graph_ms = int((time.perf_counter() - t_graph_start) * 1000)

                session_id = f"wekatrace{trace_index}_{trace.id}"
                sessions.append(
                    ReplaySession(
                        session_id=session_id,
                        source_id=trace.id,
                        session_index=trace_index,
                        graph=graph,
                    )
                )
                self._emit_compile_timing(
                    "trace_compile",
                    {
                        "trace_id": trace.id,
                        "trace_index": trace_index,
                        "execution_mode": "sequential",
                        "reconstruct_raw_calls_ms": reconstruct_raw_calls_ms,
                        "build_graph_ms": build_graph_ms,
                        "trace_total_ms": int((time.perf_counter() - t_trace_start) * 1000),
                        "raw_call_count": len(raw_calls),
                        "event_count": len(graph.events),
                    },
                )
            except Exception as e:
                logger.error(f"Failed to process Weka trace {trace.id}: {e}")
                if not self.weka_config.skip_invalid_files:
                    raise

        return sessions

    def _build_sessions_from_traces_parallel(self, traces: List[WekaTrace]) -> List[ReplaySession]:
        sessions: List[ReplaySession] = []
        failed_trace_ids: List[str] = []
        compile_workers = self.weka_config.compile_workers
        if compile_workers <= 0:
            compile_workers = os.cpu_count() or 1
        compile_workers = max(1, min(compile_workers, len(traces)))
        inflight_limit = self.weka_config.compile_inflight_limit
        if inflight_limit is None:
            inflight_limit = self.weka_config.compile_chunk_size
        inflight_limit = max(1, min(inflight_limit, len(traces)))
        self._emit_compile_timing(
            "session_build_mode",
            {
                "effective_mode": "process",
                "trace_count": len(traces),
                "effective_compile_workers": compile_workers,
                "compile_chunk_size": self.weka_config.compile_chunk_size,
                "compile_inflight_limit": inflight_limit,
            },
        )

        tokenizer_instance = self.tokenizer.get_tokenizer()
        tokenizer_name_or_path = getattr(tokenizer_instance, "name_or_path", "")
        if not tokenizer_name_or_path:
            logger.warning(
                "Weka compile parallelism requested but tokenizer has no name_or_path; falling back to sequential compilation"
            )
            self._emit_compile_timing(
                "session_build_mode",
                {
                    "effective_mode": "sequential_fallback_no_tokenizer_name",
                    "trace_count": len(traces),
                },
            )
            for trace_index, trace in enumerate(traces):
                try:
                    t_trace_start = time.perf_counter()
                    t_reconstruct_start = time.perf_counter()
                    raw_calls = self._reconstruct_raw_calls(trace)
                    reconstruct_raw_calls_ms = int((time.perf_counter() - t_reconstruct_start) * 1000)
                    if not raw_calls:
                        self._emit_compile_timing(
                            "trace_compile",
                            {
                                "trace_id": trace.id,
                                "trace_index": trace_index,
                                "execution_mode": "sequential_fallback_no_tokenizer_name",
                                "reconstruct_raw_calls_ms": reconstruct_raw_calls_ms,
                                "build_graph_ms": 0,
                                "trace_total_ms": int((time.perf_counter() - t_trace_start) * 1000),
                                "raw_call_count": 0,
                                "event_count": 0,
                            },
                        )
                        continue
                    t_graph_start = time.perf_counter()
                    graph = build_graph(raw_calls, source_file=f"weka_trace_{trace.id}")
                    build_graph_ms = int((time.perf_counter() - t_graph_start) * 1000)
                    sessions.append(
                        ReplaySession(
                            session_id=f"wekatrace{trace_index}_{trace.id}",
                            source_id=trace.id,
                            session_index=trace_index,
                            graph=graph,
                        )
                    )
                    self._emit_compile_timing(
                        "trace_compile",
                        {
                            "trace_id": trace.id,
                            "trace_index": trace_index,
                            "execution_mode": "sequential_fallback_no_tokenizer_name",
                            "reconstruct_raw_calls_ms": reconstruct_raw_calls_ms,
                            "build_graph_ms": build_graph_ms,
                            "trace_total_ms": int((time.perf_counter() - t_trace_start) * 1000),
                            "raw_call_count": len(raw_calls),
                            "event_count": len(graph.events),
                        },
                    )
                except Exception as e:
                    logger.error(f"Failed to process Weka trace {trace.id}: {e}")
                    if not self.weka_config.skip_invalid_files:
                        raise
            return sessions

        logger.info(
            "Weka compile parallelism enabled: mode=process workers=%d inflight_limit=%d traces=%d",
            compile_workers,
            inflight_limit,
            len(traces),
        )
        t0 = time.perf_counter()
        session_by_trace_index: Dict[int, ReplaySession] = {}
        with ProcessPoolExecutor(max_workers=compile_workers) as executor:
            traces_with_indices = list(enumerate(traces))
            next_submit_idx = 0
            in_flight: Dict[Any, Tuple[int, WekaTrace, float]] = {}

            def submit_one(trace_index: int, trace: WekaTrace) -> None:
                fut = executor.submit(
                    _build_trace_session_in_process,
                    trace_index,
                    trace,
                    base_seed=self.base_seed,
                    tokenized_corpus=self._tokenized_corpus,
                    default_block_size=self.weka_config.default_block_size,
                    trace_idle_gap_cap_seconds=self.weka_config.trace_idle_gap_cap_seconds,
                    use_static_model=self.weka_config.use_static_model,
                    static_model_name=self.weka_config.static_model_name,
                    model_mapping=self.weka_config.model_mapping,
                    tokenizer_name_or_path=tokenizer_name_or_path,
                )
                in_flight[fut] = (trace_index, trace, time.perf_counter())

            initial_submit = min(inflight_limit, len(traces_with_indices))
            for _ in range(initial_submit):
                trace_index, trace = traces_with_indices[next_submit_idx]
                submit_one(trace_index, trace)
                next_submit_idx += 1

            while in_flight:
                done, _ = wait(list(in_flight.keys()), return_when=FIRST_COMPLETED)
                for future in done:
                    trace_index, trace, submit_time = in_flight.pop(future)
                    try:
                        session, trace_timing = future.result()
                        if session is not None:
                            session_by_trace_index[trace_index] = session
                        trace_timing["execution_mode"] = "process"
                        trace_timing["scheduler_queue_wait_ms"] = int((time.perf_counter() - submit_time) * 1000)
                        self._emit_compile_timing("trace_compile", trace_timing)
                    except Exception as e:
                        logger.error(f"Failed to process Weka trace {trace.id} in parallel: {e}")
                        failed_trace_ids.append(trace.id)
                        if not self.weka_config.skip_invalid_files:
                            raise

                    if next_submit_idx < len(traces_with_indices):
                        next_trace_index, next_trace = traces_with_indices[next_submit_idx]
                        submit_one(next_trace_index, next_trace)
                        next_submit_idx += 1

                self._emit_compile_timing(
                    "compile_batch",
                    {
                        "batch_start_index": 0,
                        "batch_size": len(in_flight),
                        "batch_elapsed_ms": 0,
                        "scheduler_event": "inflight_refill",
                        "submitted_so_far": next_submit_idx,
                    },
                )

        for trace_index in sorted(session_by_trace_index.keys()):
            sessions.append(session_by_trace_index[trace_index])

        elapsed_ms = int((time.perf_counter() - t0) * 1000)
        logger.info(
            "Weka parallel compile completed in %d ms (sessions=%d failed=%d)",
            elapsed_ms,
            len(sessions),
            len(failed_trace_ids),
        )
        return sessions

    @staticmethod
    def _merge_headers_case_insensitive(target: Dict[str, str], source: Dict[str, str]) -> None:
        for key, value in source.items():
            key_lower = key.lower()
            matching_keys = [existing for existing in target.keys() if existing.lower() == key_lower]
            for existing in matching_keys:
                del target[existing]
            target[key] = value

    def load_lazy_data(self, data: Any) -> Any:
        api_data = super().load_lazy_data(data)
        session_id = getattr(api_data, "session_id", None) or getattr(data, "session_id", None)
        if not session_id:
            return api_data

        session_headers = self._session_headers_by_session_id.get(session_id)
        if not session_headers:
            return api_data

        if api_data.headers is None:
            api_data.headers = {}

        self._merge_headers_case_insensitive(api_data.headers, session_headers)
        if session_id not in self._logged_header_sessions:
            logger.info(
                "Applied %d session header(s) for session %s (session headers override global/static headers)",
                len(session_headers),
                session_id,
            )
            self._logged_header_sessions.add(session_id)
        return api_data

    def _reconstruct_raw_calls(self, trace: WekaTrace) -> List[RawCall]:
        assert self.tokenizer is not None
        tokenizer_instance = self.tokenizer.get_tokenizer()

        def decode_tokens_to_text(tokens: List[int]) -> str:
            decoded = tokenizer_instance.decode(tokens)
            return decoded if isinstance(decoded, str) else " ".join(decoded)

        return _reconstruct_raw_calls_shared(
            trace,
            base_seed=self.base_seed,
            tokenized_corpus=self._tokenized_corpus,
            default_block_size=self.weka_config.default_block_size,
            trace_idle_gap_cap_seconds=self.weka_config.trace_idle_gap_cap_seconds,
            decode_tokens_to_text=decode_tokens_to_text,
            use_static_model=self.weka_config.use_static_model,
            static_model_name=self.weka_config.static_model_name,
            model_mapping=self.weka_config.model_mapping,
        )

    def _build_model_map(self, trace: WekaTrace) -> Dict[str, str]:
        """Maps trace-side models to configured api_config or target models."""
        configured = self.weka_config.model_mapping or {}
        if self.weka_config.use_static_model:
            return {m: self.weka_config.static_model_name for m in trace.models}
        return configured
